### ISSUE TITLE
Runtime error in plotting branch

### ISSUE THREAD

**Issue by MJC598** [vinayguntu/LUT_Prelim#16]
When running the command: python run_bionet.py jsons/simulation_config.json on the plotting branch this error is generated. The x86_64 files have to be recompiled using nrnivmodl to fix the compatability errors in the .o/.c/.mod files

2021-05-03 13:48:30,082 [INFO]     step:20000 t_sim:2000.00 ms
2021-05-03 13:48:30,085 [INFO] PGN firing rate = 3.00 Hz
2021-05-03 13:48:30,086 [INFO] Volume = 0.07 ml
2021-05-03 13:48:30,086 [INFO] Pressure = 9.97 cm H20
2021-05-03 13:48:30,086 [INFO] Bladder afferent firing rate = 0.48 Hz
Traceback (most recent call last):
  File "/home/matt/anaconda3/envs/lut_vinnay/lib/python3.6/site-packages/bmtk/simulator/bionet/biosimulator.py", line 381, in post_fadvance
    mod.block(self, time_step_interval)
  File "/home/matt/repos/LUT_Prelim/feedback_loop.py", line 324, in block
    self._activate_hln(sim, block_interval, bladaff_fr)
  File "/home/matt/repos/LUT_Prelim/feedback_loop.py", line 61, in _activate_hln
    spikes = psg.get_times(0)*1000 # convert sec to ms
  File "/home/matt/anaconda3/envs/lut_vinnay/lib/python3.6/site-packages/bmtk/utils/reports/spike_trains/spike_train_buffer.py", line 153, in get_times
    pop = self._pops[population]
KeyError: '<sonata:none>'
NEURON: PyObject method call failed: post_fadvance
 near line 0
 ^
        advance()
      step()
    continuerun(60500)
  run(60500)
Traceback (most recent call last):
  File "run_bionet.py", line 55, in <module>
    run(sys.argv[-1])
  File "run_bionet.py", line 46, in run
    sim.run()
  File "/home/matt/anaconda3/envs/lut_vinnay/lib/python3.6/site-packages/bmtk/simulator/bionet/biosimulator.py", line 342, in run
    h.run(h.tstop)        # <- runs simuation: works in parallel
RuntimeError: hoc error

**Comment by MJC598** [comment]
This has since been noticed on master. It only happens occasionally and likely has to do with parallel execution differences between hardwares (specifically if its running on a CPU vs GPU).
